import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class RecipeServiceService {
  recipes = [
    {
      title: 'Spaghetti Carbonara',
      image:
        'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1001491_11-2e0fa5c.jpg?quality=90&resize=440,400',
      ingredients: [
        'spaghetti',
        'eggs',
        'parmesan cheese',
        'pancetta',
        'black pepper',
      ],
      timeToComplete: '30 minutes',
      procedure: [
        'Cook the spaghetti in salted boiling water.',
        'Fry the pancetta until crispy.',
        'Mix eggs and parmesan cheese in a bowl.',
        'Combine the spaghetti with the pancetta, then add the egg mixture off the heat.',
        'Season with black pepper and serve.',
      ],
      category: 'non-veg',
      rating: '10',
    },
    {
      title: 'Margherita Pizza',
      image:
        'https://recipes.timesofindia.com/thumb/56868564.cms?width=1200&height=900',
      ingredients: [
        'pizza dough',
        'tomato sauce',
        'mozzarella cheese',
        'basil leaves',
        'olive oil',
      ],
      timeToComplete: '1 hour',
      procedure: [
        'Preheat the oven to 475°F (245°C).',
        'Roll out the pizza dough on a floured surface.',
        'Spread tomato sauce over the dough.',
        'Sprinkle mozzarella cheese on top.',
        'Bake for 10-12 minutes until the crust is golden and the cheese is bubbly.',
        'Add fresh basil leaves and drizzle with olive oil before serving.',
      ],
      category: 'veg',
      rating: '7',
    },
    {
      title: 'Chicken Tikka Masala',
      image: 'chicken_tikka_masala.jpg',
      ingredients: [
        'chicken',
        'yogurt',
        'garlic',
        'ginger',
        'tomato puree',
        'cream',
        'spices',
      ],
      timeToComplete: '1 hour 30 minutes',
      procedure: [
        'Marinate the chicken in yogurt, garlic, ginger, and spices for at least 1 hour.',
        'Grill the marinated chicken until cooked through.',
        'Prepare the sauce with tomato puree, cream, and spices.',
        'Combine the grilled chicken with the sauce and simmer for 20 minutes.',
        'Serve with rice or naan.',
      ],
      category: 'non-veg',
    },
    {
      title: 'Vegetable Stir Fry',
      image: 'vegetable_stir_fry.jpg',
      ingredients: [
        'broccoli',
        'carrots',
        'bell peppers',
        'soy sauce',
        'ginger',
        'garlic',
        'sesame oil',
      ],
      timeToComplete: '20 minutes',
      procedure: [
        'Heat sesame oil in a wok or large pan.',
        'Add garlic and ginger, sauté for 1 minute.',
        'Add broccoli, carrots, and bell peppers, and stir-fry for 5-7 minutes.',
        'Add soy sauce and cook for another 2 minutes.',
        'Serve hot with rice or noodles.',
      ],
      category: 'veg',
    },
    {
      title: 'Beef Tacos',
      image: 'beef_tacos.jpg',
      ingredients: [
        'ground beef',
        'taco seasoning',
        'taco shells',
        'lettuce',
        'tomato',
        'cheese',
        'sour cream',
      ],
      timeToComplete: '25 minutes',
      procedure: [
        'Cook ground beef in a pan until browned.',
        'Add taco seasoning and water, and simmer for 10 minutes.',
        'Warm taco shells in the oven or microwave.',
        'Fill taco shells with beef mixture, lettuce, tomato, cheese, and sour cream.',
        'Serve immediately.',
      ],
      category: 'non-veg',
    },
    {
      title: 'Caprese Salad',
      image: 'caprese_salad.jpg',
      ingredients: [
        'tomatoes',
        'mozzarella cheese',
        'basil leaves',
        'olive oil',
        'balsamic vinegar',
        'salt',
        'pepper',
      ],
      timeToComplete: '10 minutes',
      procedure: [
        'Slice tomatoes and mozzarella cheese.',
        'Arrange tomato and mozzarella slices alternately on a plate.',
        'Top with fresh basil leaves.',
        'Drizzle with olive oil and balsamic vinegar.',
        'Season with salt and pepper to taste.',
      ],
      category: 'veg',
    },
    {
      title: 'Butter Chicken',
      image: 'butter_chicken.jpg',
      ingredients: [
        'chicken',
        'butter',
        'tomato puree',
        'cream',
        'garlic',
        'ginger',
        'spices',
      ],
      timeToComplete: '1 hour 15 minutes',
      procedure: [
        'Marinate the chicken with garlic, ginger, and spices for at least 1 hour.',
        'Cook the chicken in a pan until golden brown.',
        'Prepare the sauce with butter, tomato puree, cream, and spices.',
        'Add the chicken to the sauce and simmer for 20 minutes.',
        'Serve with rice or naan.',
      ],
      category: 'non-veg',
    },
    {
      title: 'Vegetable Curry',
      image: 'vegetable_curry.jpg',
      ingredients: [
        'potatoes',
        'carrots',
        'peas',
        'coconut milk',
        'curry powder',
        'onion',
        'garlic',
        'ginger',
      ],
      timeToComplete: '40 minutes',
      procedure: [
        'Heat oil in a pan and sauté onions, garlic, and ginger.',
        'Add curry powder and cook for 1 minute.',
        'Add potatoes and carrots, and cook for 5 minutes.',
        'Pour in coconut milk and simmer for 20 minutes.',
        'Add peas and cook for another 5 minutes.',
        'Serve hot with rice or bread.',
      ],
      category: 'veg',
    },
    {
      title: 'Shrimp Scampi',
      image: 'shrimp_scampi.jpg',
      ingredients: [
        'shrimp',
        'garlic',
        'butter',
        'white wine',
        'lemon juice',
        'parsley',
        'spaghetti',
      ],
      timeToComplete: '30 minutes',
      procedure: [
        'Cook spaghetti in salted boiling water.',
        'In a pan, melt butter and sauté garlic.',
        'Add shrimp and cook until pink.',
        'Pour in white wine and lemon juice, and simmer for 5 minutes.',
        'Combine with cooked spaghetti and garnish with parsley.',
        'Serve immediately.',
      ],
      category: 'non-veg',
    },
    {
      title: 'Paneer Butter Masala',
      image: 'paneer_butter_masala.jpg',
      ingredients: [
        'paneer',
        'butter',
        'tomato puree',
        'cream',
        'garlic',
        'ginger',
        'spices',
      ],
      timeToComplete: '45 minutes',
      procedure: [
        'Fry paneer cubes until golden brown.',
        'Prepare the sauce with butter, tomato puree, cream, garlic, ginger, and spices.',
        'Add the fried paneer to the sauce and simmer for 10 minutes.',
        'Serve hot with rice or naan.',
      ],
      category: 'veg',
    },
  ];

  constructor() {}
}
